### ISSUE TITLE
Uncaught ReferenceError: ConvenientFormSet is not defined

### ISSUE THREAD

**Issue by ukadmin** [tiesjan/django-convenient-formsets#2]
Hi,
trying to use your Module but don't see any forms. 
if i copy paste your code i get the Error:

`NameError: name 'ConvenientBaseFormset' is not defined. Did you mean: 'ConvenientBaseFormSet'?`

when i change it to "ConvenientBaseFormSet" it works, but don't see any form. 
In my Console i get the error:

`Uncaught ReferenceError: ConvenientFormset is not defined`

What's wrong here?

**Comment by tiesjan** [comment]
Thanks for reporting this. It seems the documentation contained a few spelling mistakes, causing the first error you report. They have been fixed.

As for the second error: it sounds like the JavaScript that comes with this library is not loaded properly. Are you including the formset's media in the template: `{{ formset.media }}`?
