### ISSUE TITLE
Minified file missing

### ISSUE THREAD

**Issue by martinmanzo** [tiesjan/django-convenient-formsets#8]
Hello, whenever I run the app with `DEBUG = False` I get a `404` when the browser tries to load `convenient_formsets/convenient_formsets.min.js`

I can't find that file in the repo. Maybe I'm missing something. For the moment I'm manually copying the file and changing it's name after a collectstatic.

This seems to be the line where the error is introduced: https://github.com/tiesjan/django-convenient-formsets/blob/main/convenient_formsets/formsets.py#L15

Regards,

Martín

**Comment by tiesjan** [comment]
That file is indeed not to be found in the repository. It is built [when publishing](https://github.com/tiesjan/django-convenient-formsets/blob/b4a67056a0ea4f9fe42429caeace530a3d5a3b75/.github/workflows/publish_package.yml#L38-L39) a new version of the package on PyPI, using [this command](https://github.com/tiesjan/django-convenient-formsets/blob/b4a67056a0ea4f9fe42429caeace530a3d5a3b75/package.json#L16).

I have double checked the published package and the file is indeed present. If you install the package from PyPI, Django should automatically collect it. Could it be that you're cloning the repository instead?

**Comment by martinmanzo** [comment]
Yep, that's the problem. Sorry for the inconvinience. We need the package to be compatible with Django 3 so we forked it.

Sorry and thanks!!
